Importar as bibliotecas do Pandas, Numpy, Sklearn

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
#from sklearn.preprocessing import MinMaxScaler

**Leitura do conjunto de dados**

In [ ]:
rawData = pd.read_csv("sample_data/students2.csv")

Atributos e seus valores no conjunto de dados:

Performance {'Excellent','Vg','Good','Average'}
Gender {'male','female'}
Caste {'General','OBC','SC','ST'}
coaching {'NO','WA','OA'}
time {'ONE','TWO','THREE','FOUR','FIVE','SEVEN'}
Class_ten_education {'SEBA','OTHERS','CBSE'}
twelve_education {'AHSEC','CBSE','OTHERS'}
medium' {'ENGLISH','OTHERS','ASSAMESE'}
Class_ X_Percentage {'Excellent','Vg','Good','Average'}
Class_XII_Percentage {'Excellent','Vg','Good','Average'}
Father_occupation {'DOCTOR','SCHOOL_TEACHER','BUSINESS','COLLEGE_TEACHER','OTHERS','BANK_OFFICIAL','ENGINEER','CULTIVATOR'}
Mother_occupation {'OTHERS','HOUSE_WIFE','SCHOOL_TEACHER','DOCTOR','COLLEGE_TEACHER','BANK_OFFICIAL','BUSINESS','CULTIVATOR','ENGINEER'}

In [ ]:
print(rawData.head())

  Performance Gender  ... Father_occupation Mother_occupation
0   Excellent   male  ...            DOCTOR            OTHERS
1   Excellent   male  ...    SCHOOL_TEACHER        HOUSE_WIFE
2   Excellent   male  ...          BUSINESS        HOUSE_WIFE
3   Excellent   male  ...    SCHOOL_TEACHER    SCHOOL_TEACHER
4   Excellent   male  ...   COLLEGE_TEACHER        HOUSE_WIFE

[5 rows x 12 columns]

Verificar a quantidade de instâncias e atributos

In [ ]:
print(rawData.shape)

(666, 12)

Remover instâncias com valores ausentes

In [ ]:
rawData = rawData.replace('?',np.NaN)
rawData = rawData.dropna(axis=0)

Ver os atributos do conjunto de dados

In [ ]:
attributes = rawData.columns

Verificar os valores e suas frequências no atributo 'time'

In [ ]:
print(rawData['time'].value_counts())

TWO      368
ONE      199
THREE     86
FOUR      11
FIVE       1
SEVEN      1
Name: time, dtype: int64

Converte atributos categórico ordinal para numérico (inteiro)

---

In [ ]:
#converte atributo time de objeto para categórico
rawData['time'] = pd.Categorical(rawData['time'])

rawData['time_num'] = rawData['time'].cat.codes

In [ ]:
print(rawData.head())

rawData = rawData.drop(['time'],axis=1)

  Performance Gender    Caste  ... Father_occupation Mother_occupation time_num
0   Excellent   male  General  ...            DOCTOR            OTHERS        2
1   Excellent   male      OBC  ...    SCHOOL_TEACHER        HOUSE_WIFE        5
2   Excellent   male      OBC  ...          BUSINESS        HOUSE_WIFE        5
3   Excellent   male  General  ...    SCHOOL_TEACHER    SCHOOL_TEACHER        2
4   Excellent   male  General  ...   COLLEGE_TEACHER        HOUSE_WIFE        5

[5 rows x 13 columns]

In [ ]:
print(rawData.head())

  Performance Gender    Caste  ... Father_occupation Mother_occupation time_num
0   Excellent   male  General  ...            DOCTOR            OTHERS        2
1   Excellent   male      OBC  ...    SCHOOL_TEACHER        HOUSE_WIFE        5
2   Excellent   male      OBC  ...          BUSINESS        HOUSE_WIFE        5
3   Excellent   male  General  ...    SCHOOL_TEACHER    SCHOOL_TEACHER        2
4   Excellent   male  General  ...   COLLEGE_TEACHER        HOUSE_WIFE        5

[5 rows x 12 columns]

Conversão de um atributo nominal para atributo binário (dummy variables)

In [ ]:
rawData = pd.get_dummies(rawData)

print(rawData.head())

   time_num  ...  Mother_occupation_SCHOOL_TEACHER
0         2  ...                                 0
1         5  ...                                 0
2         5  ...                                 0
3         2  ...                                 1
4         5  ...                                 0

[5 rows x 48 columns]

In [ ]:
rawData

     time_num  ...  Mother_occupation_SCHOOL_TEACHER
0           2  ...                                 0
1           5  ...                                 0
2           5  ...                                 0
3           2  ...                                 1
4           5  ...                                 0
..        ...  ...                               ...
661         2  ...                                 0
662         4  ...                                 0
663         5  ...                                 1
664         4  ...                                 0
665         2  ...                                 0

[666 rows x 48 columns]

In [ ]:
X = rawData.values

print(X)

[[2 0 1 ... 0 1 0]
 [5 0 1 ... 1 0 0]
 [5 0 1 ... 1 0 0]
 ...
 [5 1 0 ... 0 0 1]
 [4 1 0 ... 1 0 0]
 [2 1 0 ... 0 1 0]]

In [ ]:
attributes_dummies = rawData.columns

normalize = preprocessing.MinMaxScaler()
xscaled = normalize.fit_transform(X)

dados_tratados = pd.DataFrame(xscaled,columns=attributes_dummies)

dados_tratados

     time_num  ...  Mother_occupation_SCHOOL_TEACHER
0         0.4  ...                               0.0
1         1.0  ...                               0.0
2         1.0  ...                               0.0
3         0.4  ...                               1.0
4         1.0  ...                               0.0
..        ...  ...                               ...
661       0.4  ...                               0.0
662       0.8  ...                               0.0
663       1.0  ...                               1.0
664       0.8  ...                               0.0
665       0.4  ...                               0.0

[666 rows x 48 columns]